apiVersion: v1
kind: LimitRange 
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default:
      memory: 1Gi
    deafultRequest:
      memoty: 1Gii
    max: 
      memory: 1Gi
    min: 
      memory: 500Mi
    type: Container
