apiVersion: v1
kind: LimitRange
metadata: 
  name: cpu-resource-constraint
spec:
  limits: 
  - default:  # limit 
      cpu: 500m
    defaultRequest: # request 
      cpu: 500m
    max:  # max for limit in containers
      cpu: "1"
    min: # min for request in containers
      cpu: 100m
    type: Container
