apiVersion: v1
kind: Pod 
metadata: 
  name: frontend
spec:
  containers:
  - name: app
    image: mages.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits: 
        memory: "128Mi"
        cou: "500m"
  - name: log-aggreagator
    image: images.my-company.example/log-aggregator:v6
    resources:
      request:
        memory: "64Mi"
        cpu: "250m"
      limits: 
        memory: "128Mi"
        cpu: "500m" 
