apiVersion: v1
kind: Pod 
metadata: 
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports: 
    - containerPort: 8080
  
  readinessProbe: # http test 
    httpGet:
      path: /api/ready
      port: 8080
    initialDelaySeconds: 10 # start probe after 10 seconds 
    periodSeconds: 5 # and delay for 5 sec
    failureThreshold: 8 # default tries 3 attempts 
    
  readinessProbe: # TCP test 
    tcpSocket:
      port: 3306

  readinessProbe: # exec command 
    exec:
      command: 
      - cat
      - /app/is_ready # command in array format