apiVersion: v1
kind: ServiceAccount
metadata: 
  name: nginx-ingress-serviceaccount
# ingress controller have additional intelligence built into them to monitor the k8s cluster
# for ingress resources and configure underlying NGINX server when smth is changed
# but to do this it requires a service account with the right set of permissions
# Roles, ClusterRoles, RoleBindings